typography_spectrum: 0.646909135626629
color:
  brandStrength: 0.5797976304311305
  lightness: 0.7593555152416229
  saturation: 0.3055918619502336
  rhythmicContrast: 0.9563835100270808
  brandColors:
    - '#1C1D21'
    - '#31353D'
    - '#445878'
    - '#92CDCF'
    - '#EEEFF7'
layout_spectrum: 0.13952215039171278
name: Dentist in Bristol
navigation:
  - name: contact us
    url: www.ckdental.co.uk
    type: external
  - name: Dental Implants in Bristol
    id: c5411cc6-b26a-42ab-a538-8f15105bc9c8
    type: content
  - name: GA for Dental Procedures
    id: 5e0a6112-ac02-4480-a0ea-417176bc94d1
    type: content
  - name: Crowns and Bridges
    id: 9460fc63-5ea5-4a47-9a8f-107f1207fe46
    type: content
  - name: Team
    id: d9db5e07-06e0-4a14-97c2-0da1fd4e1832
    type: content
title: Dentist in Bristol
description: Complete Dental  Care
